name: assignment-test
on:
    # push:        
    #     branches:
    #         - 'develop'
    #         - 'main'
    pull_request:
        branches:
            - 'develop'
            - 'main'
jobs:
      build:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run build
            timeout-minutes: 600
            run: source ./build.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D