name: assignment-test
on:
    push:        
        branches:
            - 'develop'
            - 'main'
        paths-ignore:
            - 'docs/**'
            - 'README.md'
            - 'LICENSE'
    pull_request:
        branches:
            - 'develop'
            - 'main'
        paths-ignore:
            - 'docs/**'
            - 'README.md'
            - 'LICENSE'
            
jobs:
      build:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Build Kernel and RootFS
            timeout-minutes: 600
            run: source ./build.sh "raspberrypi4-64"
          - name: Flash SD Card
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            timeout-minutes: 30
            run: source ./flash.sh "raspberrypi4-64" "/dev/sdb"
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D