# Board and I2C configuration for AESD layer
MACHINE ?= "raspberrypi4-64"

# Enable I2C hardware interface in device tree
ENABLE_I2C = "1"

# Enable I2C on GPIO pins (I2C1)
RPI_EXTRA_CONFIG:append = "\n dtparam=i2c_arm=on"

KERNEL_MODULE_AUTOLOAD:raspberrypi4-64 = " i2c-dev i2c-bcm2708"
