# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"


BBFILE_COLLECTIONS += "meta-aesd"
BBFILE_PATTERN_meta-aesd = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aesd = "6"

LAYERDEPENDS_meta-aesd = "core"
LAYERSERIES_COMPAT_meta-aesd = "hardknott kirkstone"

# I2C configuration for AESD layer
# Enable I2C hardware interface in device tree
ENABLE_I2C = "1"

# Enable I2C on GPIO pins (I2C1) and LCD1602 overlay
# RPI_EXTRA_CONFIG:append = "\ndtparam=i2c_arm=on"
RPI_EXTRA_CONFIG:append = "\ndtoverlay=lcd1602-overlay"
RPI_EXTRA_CONFIG:append = "\ndtoverlay=i2c-gpio,i2c_gpio_sda=2,i2c_gpio_scl=3,i2c_gpio_delay_us=2,bus=1"